openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - url: http://localhost:3000/
    description:  Local server 
  - url: https://hr-portal-nd68.onrender.com/
    description:  Pre Production server
info:
  version: "1.0.0"
  title: HR Portal
  description: The API for the  HR Portal
paths:
  /auth/api/employee/login:
   post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "pr@gmail.com"
                password:
                  type: string
                  example: "secret..."
      responses: 
        '200':
          description: OK
  /auth/api/employee/sign-up:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                email:
                  type: string
                  example: "pr@gmail.com"
                firstName:
                  type: string
                lastName:
                 type: string
                password:
                  type: string
                  example: "secret"
      responses: 
        '200':
          description: OK
      responses: 
        '200':
          description: OK

  /api/employee-list:
    get:
      tags:
        - Employee
      responses: 
        '200':
          description: OK